library(dplyr)
demo<-read.csv('demographics.csv')
View(demo)
# Se selecciona en la calumna de marital solo a los que estan casados
demo2<-select(demo,age, marital, gender)
demo2<-select(demo, income:carcat)
demo2<-select(demo, c(3:5))
demo2<-select(demo, -age, -income)
demo2<-select(demo, -6, -8)
demo2<-select(demo, -1:-3)
demo2<-select(demo, contains('ret'))
demo2<-select(demo, starts_with('in'))
demo2<-select(demo, ends_with('cat'))
View(demo2)
